[package]
name = "simple-async-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12.3"
pin-utils = "0.1.0"
tokio = { version = "1.41.0", default-features = false, features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.41.0", features = ["full"] }
